# Generated by Django 4.2 on 2023-05-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_imagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='new_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
