# Generated by Django 4.2 on 2023-05-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_imagedata_new_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagedata',
            options={'ordering': ['new_time']},
        ),
        migrations.AddField(
            model_name='imagedata',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
