# Generated by Django 4.2 on 2023-05-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_imagedata_options_imagedata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='新增日期'),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='上傳圖片(不可更動)'),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='name_image',
            field=models.CharField(max_length=100, verbose_name='圖片名稱'),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='new_time',
            field=models.DateTimeField(auto_now=True, verbose_name='新增日期時間'),
        ),
    ]
