# Generated by Django 4.2 on 2023-05-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_imagedata_date_alter_imagedata_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='上傳圖片'),
        ),
    ]
