# Generated by Django 4.2 on 2023-07-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_imagedata_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onTime', models.CharField(max_length=10)),
                ('offTime', models.CharField(max_length=10)),
                ('onTime_2', models.CharField(blank=True, max_length=10, null=True)),
                ('onTime_3', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
