# Generated by Django 4.2 on 2023-07-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_setting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='onTime_2',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='onTime_3',
        ),
    ]
